LoginTests/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('lg.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lg/urls.py
from django.conf.urls import url

from . import views

app_name = 'lg'

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

lg/models.py
from django.contrib.auth.models import User
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    age = models.IntegerField(default=0)
    desc = models.CharField(max_length=140,blank=True)
    avatar = models.ImageField(upload_to='avatars/',default='avatars/default.png')

lg/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms.models import ModelForm

from .models import UserProfile


class ProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ('age', 'desc', 'avatar')


class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'password', 'email')

    def save(self, commit=True):
        new_user = User.objects.create_user(self.cleaned_data['username'],
                                            self.cleaned_data['email'],
                                            self.cleaned_data['password'])
        # new_user.first_name = self.cleaned_data['first_name']
        # new_user.last_name = self.cleaned_data['last_name']
        if commit:
            new_user.save()
        return new_user

lg/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect
# Create your views here.
from django.views.generic import TemplateView
from django.views.generic.base import View

from .forms import ProfileForm
from .forms import UserForm


# @receiver(post_save, sender=User)
# def create_profile(sender, instance , created, **kwargs):
#     if created:
#         UserProfile.objects.create(user=instance)
#
# @receiver(post_save, sender=User)
# def save_profile(sender, instance , **kwargs):
#     print(dir(instance))
#     instance.userprofile.save()

class Index(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        ctx = {}
        ctx['loggedIn'] = False
        if self.request.user.is_authenticated:
            ctx['loggedIn'] = True
        return ctx


class SignUpView(TemplateView):
    template_name = 'signup.html'

    def get_context_data(self, **kwargs):
        ctx = super(SignUpView, self).get_context_data(**kwargs)
        ctx['user_form'] = UserForm(prefix='user')
        ctx['profile_form'] = ProfileForm(prefix='profile')
        return ctx

    def post(self, request, *args, **kwargs):
        user_form = UserForm(request.POST, prefix='user')
        profile_form = ProfileForm(request.POST, request.FILES, prefix='profile')
        if profile_form.is_valid() and user_form.is_valid():
            user = user_form.save(commit=False)
            profile = profile_form.save(commit=False)
            user.save()
            profile.user = user
            profile.save()
            return HttpResponse("Signed Up!<br><a href='/'>Go to home</a>")
        else:
            return HttpResponse("Error : <a href='/signup'>Try again</a>!")


class LoginView(TemplateView):
    template_name = 'login.html'

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                return HttpResponse('Error: User authentication error <a href="/login"">Try again</a>')
        else:
            return HttpResponse('Error: Username or password is empty <a href="/login">Try again</a>')


class LogoutView(View, LoginRequiredMixin):
    def get(self, request):
        logout(request)
        return redirect('/')

lg/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
{% if loggedIn %}
    Hello {{ request.user.username }}<br>
    <br>
    <img src="{{ request.user.userprofile.avatar.url }}" style="max-height: 500px;max-width: 500px"/>
    <br>
    <p>Desciption:
        {{ request.user.userprofile.desc }}
    </p>
    <p>
        Age:{{ request.user.userprofile.age }}
    </p>

    <a href="{% url 'lg:logout' %}">Logout</a>
{% else %}
    Not logged in. <br>
    <a href="{% url 'lg:signup' %}">Sign Up</a> or <a href="{% url 'lg:login' %}">Login</a>
{% endif %}

</body>
</html>

lg/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<h1>Login</h1>
<form method="post" action="{% url 'lg:login' %}">
    {% csrf_token %}
    <p>Username: <input type="text" name="username"></p>
    <p>Passwoord: <input type="password" name="password"></p>
    <button type="submit">Login</button>
</form>
</body>
</html>

lg/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>
<body>
<h1>Sign Up</h1>
<form action="{% url 'lg:signup' %}" enctype="multipart/form-data" method="post"
      style="border: 0.4em dotted green;padding: 1em">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Submit</button>
</form>


</body>
</html>